# DIVERGES FROM THE SCAFFOLD: this file is not generated by `agents-cli infra
# single-project`, which leaves state local. See "Divergences from the scaffold" in
# README.md before running `agents-cli scaffold upgrade`.
#
# Terraform state lives in GCS, not in this directory.
#
# Bucket and prefix match exactly what `agents-cli infra cicd` would write here
# (`infra/cmd_cicd.py:316-352`): it targets `<project_id>-terraform-state` and keys
# single-project state under `<repo>/dev`, prod under `<repo>/prod`. Adopting that
# layout up front means enabling CI/CD later is a no-op rather than a state migration.
#
# The bucket is deliberately not a Terraform resource — it has to exist before the
# backend it holds can be initialised. Create it with the idempotent bootstrap script,
# which is the reproducible record of how it was made:
#   deployment/terraform/bootstrap-state-bucket.sh
terraform {
  backend "gcs" {
    bucket = "tim-platform-lab-terraform-state"
    prefix = "blueprint-agent/dev"
  }
}
